### ISSUE TITLE
Pandas requires specific version of dateutil

### ISSUE THREAD

**Issue by jmeppley** [conda-forge/pandas-feedstock#51]
Issue:
In updating another package, conda bumped me up to pandas 0.23. However, when running code, I get this error:

```
ImportError in line 27 of /data/jmeppley/projects/Aloha_2_0/workflows/annotation.gene_catalog.snake:
dateutil 2.5.0 is the minimum required version
  File "/data/jmeppley/projects/Aloha_2_0/workflows/annotation.gene_catalog.snake", line 27, in <module>
  File "/data/jmeppley/projects/Aloha_2_0/catalog/conda.env/lib/python3.5/site-packages/pandas/__init__.py", line 23, in <module>
  File "/data/jmeppley/projects/Aloha_2_0/catalog/conda.env/lib/python3.5/site-packages/pandas/compat/__init__.py", line 421, in <module>
```

Explicitly updating python-dateutil solved my problem. Should we add the requirement to the latest recipe?

<br/>
Original Environment:

<details>
I don't have the `conda list` output from the broken envirotnment, 
```
(/home/jmeppley/projects/Aloha_2_0/catalog/conda.env) [jmeppley@glutamate catalog]$ conda install -c conda-forge -c bioconda -c jmeppley "py-metagenomics=1.1.1" "pandas=0.22" "numpy=1.12"
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.9
  latest version: 4.5.11

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/jmeppley/projects/Aloha_2_0/catalog/conda.env

  added / updated specs:
    - numpy=1.12
    - pandas=0.22
    - py-metagenomics=1.1.1


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openblas-0.2.20            |                8        17.0 MB  conda-forge
    numpy-base-1.14.3          |   py35h0ea5e3f_1         4.0 MB
    numpy-1.12.1               |py35_blas_openblas_201         8.5 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        29.5 MB

The following NEW packages will be INSTALLED:

    libgfortran: 3.0.0-1               conda-forge
    libopenblas: 0.2.20-h9ac9557_7
    openblas:    0.2.20-8              conda-forge

The following packages will be UPDATED:

    biopython:       1.70-np112py35_1      bioconda    --> 1.72-py35_0           conda-forge
    ca-certificates: 2018.1.18-0           conda-forge --> 2018.8.24-ha4d7672_0  conda-forge
    certifi:         2018.1.18-py35_0      conda-forge --> 2018.8.24-py35_1      conda-forge
    numpy:           1.12.1-py35hca0bb5e_1             --> 1.14.3-py35hcd700cb_1
    openssl:         1.0.2o-0              conda-forge --> 1.0.2p-h470a237_0     conda-forge
    pandas:          0.22.0-py35_0         conda-forge --> 0.23.0-py35_0         conda-forge
    py-metagenomics: 1.0.0-py35_0          jmeppley    --> 1.1.1-py35_0          jmeppley

Proceed ([y]/n)? y


Downloading and Extracting Packages
biopython-1.72       |  2.8 MB | ############################################################################################################################ | 100%
mkl_fft-1.0.6        |  574 KB | ############################################################################################################################ | 100%
certifi-2018.8.24    |  138 KB | ############################################################################################################################ | 100%
pandas-0.23.0        | 28.9 MB | ############################################################################################################################ | 100%
py-metagenomics-1.1. |  232 KB | ############################################################################################################################ | 100%
numpy-1.14.3         |   41 KB | ############################################################################################################################ | 100%
numpy-base-1.14.3    |  4.1 MB | ############################################################################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(/home/jmeppley/projects/Aloha_2_0/catalog/conda.env) [jmeppley@glutamate catalog]$ conda list | grep date
python-dateutil           2.3                      py35_0    bioconda
```
</details>

<br/>
Simple Environment to reproduce:

I was able to reproduce the error by explicilty installing mismatched packages with:
```
conda create -n brokepanda -c conda-forge pandas "python-dateutil<2.5"
```
<details>
```
Packages installed:
. . .
The following NEW packages will be INSTALLED:

    blas:            1.0-mkl
    bzip2:           1.0.6-h470a237_2      conda-forge
    ca-certificates: 2018.8.24-ha4d7672_0  conda-forge
    certifi:         2018.8.24-py35_1      conda-forge
    intel-openmp:    2019.0-118
    libffi:          3.2.1-hfc679d8_5      conda-forge
    libgcc-ng:       7.2.0-hdf63c60_3      conda-forge
    libgfortran-ng:  7.2.0-hdf63c60_3      conda-forge
    libstdcxx-ng:    7.2.0-hdf63c60_3      conda-forge
    mkl:             2019.0-118
    mkl_fft:         1.0.6-py35_0          conda-forge
    mkl_random:      1.0.1-py35_0          conda-forge
    ncurses:         6.1-hfc679d8_1        conda-forge
    numpy:           1.15.0-py35h1b885b7_0
    numpy-base:      1.15.0-py35h3dfced4_0
    openssl:         1.0.2p-h470a237_0     conda-forge
    pandas:          0.23.0-py35_0         conda-forge
    pip:             18.0-py35_1           conda-forge
    python:          3.5.5-h5001a0f_2      conda-forge
    python-dateutil: 2.4.2-py35_0
    pytz:            2018.5-py_0           conda-forge
    readline:        7.0-haf1bffa_1        conda-forge
    setuptools:      40.4.0-py35_0         conda-forge
    six:             1.11.0-py35_1         conda-forge
    sqlite:          3.25.1-hb1c47c0_0     conda-forge
    tk:              8.6.8-ha92aebf_0      conda-forge
    wheel:           0.31.1-py35_1         conda-forge
    xz:              5.2.4-h470a237_1      conda-forge
    zlib:            1.2.11-h470a237_3     conda-forge
. . .
```

Getting the error:
```
(brokepanda) [jmeppley@glutamate ~]$ python
Python 3.5.5 | packaged by conda-forge | (default, Jul 23 2018, 23:45:43)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jmeppley/.conda/envs/brokepanda/lib/python3.5/site-packages/pandas/__init__.py", line 23, in <module>
    from pandas.compat.numpy import *
  File "/home/jmeppley/.conda/envs/brokepanda/lib/python3.5/site-packages/pandas/compat/__init__.py", line 421, in <module>
    raise ImportError('dateutil 2.5.0 is the minimum required version')
ImportError: dateutil 2.5.0 is the minimum required version
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : /home/jmeppley/projects/Aloha_2_0/catalog/conda.env
    active env location : /home/jmeppley/projects/Aloha_2_0/catalog/conda.env
            shell level : 1
       user config file : /home/jmeppley/.condarc
 populated config files :
          conda version : 4.5.9
    conda-build version : not installed
         python version : 3.6.4.final.0
       base environment : /data/jmeppley/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /data/jmeppley/miniconda3/pkgs
                          /home/jmeppley/.conda/pkgs
       envs directories : /data/jmeppley/miniconda3/envs
                          /home/jmeppley/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.9 requests/2.18.4 CPython/3.6.4 Linux/4.8.13-100.fc23.x86_64 fedora/23 glibc/2.22
                UID:GID : 2000:520
             netrc file : None
           offline mode : False
```
</details>

**Comment by jmeppley** [comment]
Hmm, it looks like the dependency has already been fixed in the recipe. It looks like the pandas 0.23.0 package doesn't have the correct dependencies and is still available. Is there a way to get rid of it or udpate it's dependencies?

It's probably not a critical issue since anyone installing from scratch will get the latest version of everything...

**Comment by TomAugspurger** [comment]
> Is there a way to get rid of it or udpate it's dependencies?

Not that I know of. Closing since this is fixed on master.
